# Generated by Django 5.1.3 on 2024-12-22 20:58

import Apps.Tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_recurso_link_alter_recurso_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=Apps.Tasks.models.ruta_tareas),
        ),
    ]
