# Generated by Django 5.1.3 on 2024-12-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0007_curso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, default='cursos/default.png', null=True, upload_to='cursos/'),
        ),
    ]
